- duckdb_engine/__init__.py
> Remove description workarounds

- duckdb_engine/__init__.py
- pyproject.toml
> Remove bridge code

- .pre-commit-config.yaml
- duckdb_engine/__init__.py
- duckdb_engine/tests/test_pandas.py
- poetry.lock
- pyproject.toml
I've written some tests for `pandas` to help in investigating the chunking issue.
> Added `test_pandas.py` to the `pytest` suite.

- .pre-commit-config.yaml
- duckdb_engine/__init__.py
- duckdb_engine/tests/test_basic.py
- duckdb_engine/tests/test_pandas.py
- pyproject.toml
Committed via https://github.com/asottile/all-repos
> Add strict mypy config

- duckdb_engine/__init__.py
- duckdb_engine/tests/test_basic.py
> Fix transaction support

- .github/workflows/pythonapp.yaml
- tox.ini
> Python 3.10

- .github/workflows/pythonapp.yaml
And use permissions object instead
> Swap back trigger

- duckdb_engine/__init__.py
this partially reverts #222, and fixes https://github.com/apache/superset/pull/19317#issuecomment-1161303805
@machow are you able to find the source which told you to remove this field at all?
> fix: restore name attribute

- duckdb_engine/__init__.py
- duckdb_engine/tests/test_basic.py
> feat: enable interval support

- README.md
- duckdb_engine/__init__.py
- duckdb_engine/tests/test_basic.py
> fix: add documentation and test for duckdb config

- duckdb_engine/tests/snapshots/snap_test_basic.py
- poetry.lock
- pyproject.toml
- deps: add snapshottest
- test: add missing assertions to tests
> refactor: improve test assertions

- duckdb_engine/__init__.py
- duckdb_engine/tests/test_basic.py
> fix: disable server side cursors

- duckdb_engine/__init__.py
- duckdb_engine/tests/test_datatypes.py
Fixes https://github.com/Mause/duckdb_engine/issues/504
> fix: correct json type mapping

- duckdb_engine/__init__.py
- duckdb_engine/tests/test_datatypes.py
> fix: properly support UUID type

- .github/workflows/pythonapp.yaml
- duckdb_engine/datatypes.py
- duckdb_engine/tests/test_datatypes.py
- tox.ini
> fix: don't reflect nested types for now

- duckdb_engine/config.py
- duckdb_engine/tests/test_integration.py
@elefeint mind looking at this?
> fix: allow motherduck to pass their special token parameter at extension load time

- duckdb_engine/__init__.py
- duckdb_engine/tests/test_basic.py
@nickcrews how does this look?
> feat: try_cast operator

- README.md
- duckdb_engine/tests/conftest.py
- duckdb_engine/tests/test_integration.py
Fixes https://github.com/Mause/duckdb_engine/issues/794
> docs: amend `register` docs

- duckdb_engine/__init__.py
Fixes https://github.com/Mause/duckdb_engine/issues/856
> fix: remove packaging requirement

- duckdb_engine/__init__.py
- duckdb_engine/tests/conftest.py
- duckdb_engine/tests/test_basic.py
Fixes https://github.com/duckdb/duckdb/issues/10322
> fix: support views in has_table

- .github/workflows/pythonapp.yaml
- .pre-commit-config.yaml
- duckdb_engine/__init__.py
- duckdb_engine/_supports.py
- duckdb_engine/tests/test_basic.py
- duckdb_engine/tests/test_datatypes.py
- duckdb_engine/tests/test_integration.py
- noxfile.py
- poetry.lock
- pyproject.toml
- **build: add noxfile.py**
- **nox workflow**
> build: add nox

- duckdb_engine/datatypes.py
Fixes https://github.com/Mause/duckdb_engine/issues/995
> fix: add new type names for 0.10.3

- duckdb_engine/datatypes.py
- duckdb_engine/tests/test_datatypes.py
Fixes https://github.com/Mause/duckdb_engine/issues/1138
When we visit a struct or union, we are handed an IdentifierProvider. Before, we just used it at this first layer, but forgot to pass it down to lower compilation steps. Now, we pass it along. This was a problem when we encountered nested dtypes, eg struct<struct<>>
Without the change, the included test fails. With the changes, it passes.
> fix: propagate kwargs through compilation nodes

- duckdb_engine/__init__.py
https://github.com/Mause/duckdb_engine/issues/1190#issuecomment-2621861864
Resolves #1190
> fix: panics in multi-threaded environments
