Mause/duckdb_engine

README.md

This PR is a continuation of the [discussion on the issue opened at `duckdb` about `SERIAL` datatypes](https://github.com/duckdb/duckdb/issues/1768). It might be helpful to include a snippet in the README to address the missing support for PostgreSQL-only datatypes like `SERIAL` and provide workarounds (like the `Sequence()` used in the existing example). I've written up some examples in this PR as suggestions.

Documentation Addressing Integer Primary Key

---

duckdb_engine/__init__.py
duckdb_engine/tests/test_basic.py
duckdb_engine/tests/test_pandas.py

This PR refactors `test_pandas.py` to add more restrained tests. The size and number of chunks are checked, and both the table name and SQL query are executed in `pd.read_sql`.

Added restraints and refactored the Pandas tests.

---

duckdb_engine/__init__.py
duckdb_engine/tests/test_pandas.py

Context: I am trying out this sqlalchemy dialect to connect DuckDB with ibis (https://github.com/ibis-project/ibis). So I might do some contributions for things I run into.
This is a first, as I ran into an error when doing a basic query:
```
else:
raise exc.InvalidRequestError(
>                   "Unknown PG numeric type: %d" % coltype
)
E               TypeError: %d format: a number is required, not str
../../../miniconda3/envs/test-duckdb/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py:525: TypeError
```
This was from the psycopg2 driver which adds a custom `_PGNumeric` type (https://github.com/sqlalchemy/sqlalchemy/blob/70a33dd32f2609f2de6421c3b28ef4cc4496fdae/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L500). But that expects that the `col_type` in the …

FIX: update colspecs to handle numeric types

---

duckdb_engine/__init__.py

This was "broken" by https://github.com/duckdb/duckdb/pull/2389 (the rowcount attribute never actually existed)

fix: Fix rowcount for duckdb version > 0.3.0

---

duckdb_engine/__init__.py

This PR sets the name in the dialect class to "duckdb". This will let SQLAlchemy identify the dialect as "duckdb" in warnings and errors (and maybe other things?).
```
from sqlalchemy import create_engine
engine = create_engine("duckdb:///:memory:")
engine.dialect.name
engine.dialect.driver
```

feat: set duckdb as dialect name

---

duckdb_engine/__init__.py

Thanks for a great package! Here's a small tweak:
* [A recent PR](https://github.com/Mause/duckdb_engine/pull/180) introduced backward-compatibility for SQLAlchemy < 1.4
* The replaced method is [being deprecated](https://github.com/zzzeek/sqlalchemy/blob/fc5c54fcd4d868c2a4c7ac19668d72f506fe821e/lib/sqlalchemy/engine/url.py#L504) and is causing deprecation warnings on newer versions of SQLAlchemy
* The [docs suggest an easy way to keep backward-compatibility](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#the-url-object-is-now-immutable) without receiving deprecation warnings in future versions
* This PR implements that suggestion
* Note: I wasn't sure how to run tests---if there's anything I should do beyond what I've already done, let me know. Perhaps GH Actions will run …

Support SQLAlchemy < 1.4 without a deprecation warning on 1.4+

---

duckdb_engine/__init__.py

SQLAlchemy 1.4 introduced the statement cache -- it might be good to
enable this once it is tested, but for the moment, it raises a warning
on every first execution which is quite noisy.
```
/home/gil/github.com/ibis-project/ibis/ibis/backends/base/sql/alchemy/__init__.py:362:
SAWarning: Dialect postgresql:psycopg2 will not make use of SQL
compilation caching as it does not set the 'supports_statement_cache'
attribute to ``True``.  This can have significant performance
implications including some performance degradations in comparison to
prior SQLAlchemy versions.  Dialect maintainers should seek to set this
attribute to True after appropriate development and testing for
SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be
set to False which will disable this warning. …
```

fix: explicitly disable statement_cache for sqlalchemy 1.4

---

duckdb_engine/__init__.py

otherwise this is populated with psycopg2

feat: override driver name

---

duckdb_engine/.isort.cfg

Has long since been moved to pyproject.toml

chore: delete isort.cfg

---

duckdb_engine/__init__.py
duckdb_engine/tests/conftest.py
duckdb_engine/tests/test_basic.py

- feat: strip comments from generated sql
- test: add canary test for comment support
- feat: warn when we find comments in the ddl
- test: add and use raises_msg decorator

fix: strip comments from generated sql

---

duckdb_engine/__init__.py
duckdb_engine/tests/test_basic.py

Extracted from #393
BEGIN_COMMIT_OVERRIDE
fix: add schema support to get_view_names
END_COMMIT_OVERRIDE

fix: correct get_view_names for older sqlalchemy 

---

duckdb_engine/__init__.py
duckdb_engine/tests/test_basic.py
duckdb_engine/tests/test_integration.py

Mostly cleaning up depreciation warnings, that are becoming hard errors in SQLA2

refactor: type cleanliness for SQLA2 support

---

README.md

Hi! I added a link to DuckDB's docs to the README (which uses JupySQL 😁). Let me know what you think!

docs: adding link to duckdb docs

---

README.md

This PR adds documentation to the readme for enabling `alembic` support.

docs: add directions for `alembic` integration

---

duckdb_engine/__init__.py
duckdb_engine/tests/snapshots/snap_test_basic.py
duckdb_engine/tests/test_basic.py

Due to having multiple databases in DuckDB, the Postgres dialect of get_schema_names has duplicates (Ex: one copy of "main" for every database, including temp and system).
This is a draft because it has no tests! I just wanted to post here to get some quick feedback and I'll definitely add some tests in the next day or two. If you have specific advice or requests for tests, definitely let me know!
I tried to only wrap things in double quotes when absolutely necessary (if there are spaces or quotes within the database or schema name). Let me know if you think this will work!
One other factor is that we could go back and edit DuckDB core's pg_namespaces catalog to include the database name as the namespace. Then we could query pg_namespaces instead of duckdb_schemas. I'm not sure if that is …

fix: qualify catalog names with schema names in get_schema_names

---

.gitignore
duckdb_engine/__init__.py
duckdb_engine/tests/test_basic.py

With the introduction of PR #835 a user might want to fully specify a schema with the database name as prefix, i.e. `"my db"."my schema"`.
This PR fixes a bug that currently prevents usage of `Dialect.has_table`, `Dialect.get_table_names`, `Dialect.get_columns`, `Dialect.get_foreign_keys` and `Dialect.get_check_constraints` when using said fully specified schema name.
I also refactored `test_get_schema_names` so there is a separate test for `get_table_names`.
Edit: This fixes https://github.com/duckdb/duckdb/issues/10033

fix: support getting table properties using schema with db name prefix

---

poetry.lock
pyproject.toml

The current pin is overly strict based on the usage of `packaging` within this project. It causes clashes with other packages which may depend on newer versions of `packaging`.

fix: relax pin on `packaging`

---

README.md

I tried to run a query using the example connection from the README and it raised an error.
This change allows running a query using the example connection attributes:
```python
engine = sa.create_engine(
'duckdb:///:memory:',
connect_args={
'read_only': True,
'config': {
'memory_limit': '500mb'
}
}
)
with engine.connect() as conn:
res = conn.execute(sa.text("select 1")).scalar_one()
```
```python-traceback
CatalogException: Catalog Error: Cannot launch in-memory database in read-only mode!
<snip>
The above exception was the direct cause of the following exception:
<snip>
ProgrammingError: (duckdb.duckdb.CatalogException) Catalog Error: Cannot launch in-memory database in read-only mode!
(Background on this error at: https://sqlalche.me/e/20/f405)
```

docs: use `read_only=False` so that example doesn't raise an exception.

---

duckdb_engine/__init__.py
duckdb_engine/tests/test_basic.py

`connect` mutates the config dictionary passed to `engine.create`.
Notably, each time it is called the `custom_user_agent` grows.
This PR clones the config and modifies the clone.

fix: avoid mutating caller's connect args (don't accumulate user_agents)

---

duckdb_engine/__init__.py
duckdb_engine/tests/test_basic.py

Fixes https://github.com/Mause/duckdb_engine/issues/1173

fix: reexport postgresql insert function

---

duckdb_engine/__init__.py
duckdb_engine/tests/test_basic.py

Fixes https://github.com/Mause/duckdb_engine/issues/1190

fix: use full list of reserved words

---

duckdb_engine/config.py

Hey @Mause,
Thanks so much for creating the SQLAlchemy driver for DuckDB 🙌 
We're going to use the driver to connect to MotherDuck, so we would like to have support for the `attach_mode` and `saas_mode` connection string parameters. They are useful for our production-level applications where we need to restrict the privileges of the MotherDuck connection.
See for details:
https://motherduck.com/docs/key-tasks/authenticating-and-connecting-to-motherduck/authenticating-to-motherduck/#using-connection-string-parameters
Do you think it would be possible to merge these in? Let me know if I can do anything else to support.
\- Finn

fix: add supported MotherDuck connection string parameters
